---
os: linux
dist: bionic
language: ruby
# Workaround https://github.com/bundler/bundler/issues/3558
before_install: gem install bundler
install: bundle install --jobs 4 --retry 2 --without development release
script: bundle exec rake
rvm:
  - 2.4.4
  - 2.5.1
  - 2.6.5
  - 2.7
env:
  - PUPPET_VERSION="~> 5.5.10"
  - PUPPET_VERSION="~> 6.5"
  - PUPPET_VERSION=">= 0"
  - PUPPET_VERSION="git://github.com/puppetlabs/puppet.git#master"
jobs:
  exclude:
    - rvm: 2.7
      env: PUPPET_VERSION="~> 5.5.10"
  allow_failures:
    - env: PUPPET_VERSION=">= 0"
    - env: PUPPET_VERSION="git://github.com/puppetlabs/puppet.git#master"
deploy:
  provider: rubygems
  api_key:
    secure: "kwxryZZ/t9EkWuYxhz3G1v+U3ZK4WdsiN0UFHDjijnAGPxqe/n+oBcNA8hOiNhjZeTFo8bADEZkL7JtdKQo9RvgStipyaS5gDHB/C1c4LOBWv4Tga21NNCAuBcE2CDtAH3+TzrZV5vv2+SpOrhKZpzZoAoR6PR1MWVWMUie/rE0="
  gem: puppet-syntax
  on:
    rvm: 2.5.1
    condition: '"$PUPPET_VERSION" = "~> 5.5.10"'
    tags: true
    all_branches: true
    repo: voxpupuli/puppet-syntax
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
